# Generated by Django 5.0.1 on 2024-01-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_subpackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='destination_images/')),
                ('discount_percentage', models.PositiveIntegerField()),
                ('country', models.CharField(max_length=100)),
            ],
        ),
    ]
